
const Jobs = [
    { title: 'Software Engineer', description: 'Develop software solutions.', location: 'New York' },
    { title: 'Data Analyst', description: 'Analyze data and provide insights.', location: 'San Francisco' },
    { title: 'Product Manager', description: 'Oversee product development.', location: 'New York' },
    { title: 'Software Engineer', description: 'Develop software solutions.', location: 'San Francisco' },
    { title: 'Software Engineer', description: 'Develop software solutions.', location: 'New York' },
    { title: 'Data Analyst', description: 'Analyze data and provide insights.', location: 'San Francisco' },
    { title: 'Product Manager', description: 'Oversee product development.', location: 'Chicago' },
    { title: 'Web Developer', description: 'Build and maintain websites.', location: 'Austin' },
    { title: 'Systems Administrator', description: 'Manage IT infrastructure.', location: 'Los Angeles' },
    { title: 'UX Designer', description: 'Design user interfaces and experiences.', location: 'Seattle' },
    { title: 'Business Analyst', description: 'Analyze business processes.', location: 'Boston' },
    { title: 'Project Manager', description: 'Lead and manage projects.', location: 'Denver' },
    { title: 'Network Engineer', description: 'Design and manage network systems.', location: 'Dallas' },
    { title: 'DevOps Engineer', description: 'Automate and improve deployment processes.', location: 'San Diego' },
    { title: 'Mobile Developer', description: 'Create mobile applications.', location: 'Atlanta' },
    { title: 'Cybersecurity Specialist', description: 'Protect systems from cyber threats.', location: 'Phoenix' },
    { title: 'Database Administrator', description: 'Manage databases and data storage.', location: 'Philadelphia' },
    { title: 'Technical Support Specialist', description: 'Provide technical support to users.', location: 'Houston' },
    { title: 'Cloud Architect', description: 'Design cloud infrastructure.', location: 'Miami' },
    { title: 'AI Engineer', description: 'Develop AI and machine learning solutions.', location: 'San Jose' },
    { title: 'QA Engineer', description: 'Test software to ensure quality.', location: 'Portland' },
    { title: 'IT Manager', description: 'Oversee IT department and projects.', location: 'Las Vegas' },
    { title: 'Salesforce Administrator', description: 'Manage Salesforce platform.', location: 'Orlando' },
    { title: 'Scrum Master', description: 'Facilitate agile development processes.', location: 'Salt Lake City' },
    { title: 'IT Consultant', description: 'Provide IT consulting services.', location: 'Minneapolis' },
    { title: 'Blockchain Developer', description: 'Develop blockchain applications.', location: 'Charlotte' },
    { title: 'Embedded Systems Engineer', description: 'Develop embedded systems.', location: 'Nashville' },
    { title: 'Game Developer', description: 'Create video games.', location: 'Los Angeles' },
    { title: 'Full Stack Developer', description: 'Develop both front-end and back-end applications.', location: 'San Francisco' },
    { title: 'Technical Writer', description: 'Write technical documentation.', location: 'Washington, D.C.' },
    { title: 'SEO Specialist', description: 'Optimize websites for search engines.', location: 'New York' },
    { title: 'Content Manager', description: 'Manage content creation and strategy.', location: 'Austin' },
    { title: 'Digital Marketing Specialist', description: 'Execute digital marketing campaigns.', location: 'Chicago' },
    { title: 'Social Media Manager', description: 'Manage social media accounts.', location: 'Boston' },
    { title: 'Graphic Designer', description: 'Create visual content.', location: 'Portland' },
    { title: 'Video Editor', description: 'Edit and produce video content.', location: 'Seattle' },
    { title: 'E-commerce Manager', description: 'Manage e-commerce platforms.', location: 'San Diego' },
    { title: 'Supply Chain Analyst', description: 'Optimize supply chain operations.', location: 'Dallas' },
    { title: 'Operations Manager', description: 'Oversee business operations.', location: 'Denver' },
    { title: 'HR Manager', description: 'Manage human resources department.', location: 'Miami' },
    { title: 'Recruiter', description: 'Find and hire new employees.', location: 'Phoenix' },
    { title: 'Training Specialist', description: 'Develop and deliver training programs.', location: 'Houston' },
    { title: 'Customer Success Manager', description: 'Ensure customer satisfaction and retention.', location: 'San Jose' },
    { title: 'Account Manager', description: 'Manage client accounts.', location: 'Las Vegas' },
    { title: 'Financial Analyst', description: 'Analyze financial data and trends.', location: 'Philadelphia' },
    { title: 'Auditor', description: 'Conduct financial and compliance audits.', location: 'Orlando' },
    { title: 'Investment Analyst', description: 'Analyze investment opportunities.', location: 'Minneapolis' },
    { title: 'Actuary', description: 'Analyze financial risks.', location: 'Salt Lake City' },
    { title: 'Banking Manager', description: 'Manage banking operations.', location: 'Charlotte' },
    { title: 'Insurance Agent', description: 'Sell insurance policies.', location: 'Nashville' },
    { title: 'Real Estate Agent', description: 'Buy and sell real estate properties.', location: 'Atlanta' },
    { title: 'Property Manager', description: 'Manage real estate properties.', location: 'Washington, D.C.' },
    { title: 'Loan Officer', description: 'Evaluate and approve loan applications.', location: 'Portland' },
    { title: 'Credit Analyst', description: 'Assess creditworthiness of applicants.', location: 'San Francisco' },
  
  ];
export default Jobs